apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operators.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    plural: operators
    singular: operator
    shortNames:
    - op
    kind: Operator
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
              age:
                type: integer
    selectableFields:
    - jsonPath: .spec.email
    - jsonPath: .spec.name
    additionalPrinterColumns:
    - jsonPath: .spec.name
      name: Name
      type: string
---
apiVersion: stable.example.com/v1
kind: Operator
metadata:
  name: operator-sample
spec:
  email: test@test.com
  name: test
  age: 20