apiVersion: v1
kind: LimitRange
metadata:
  name: sample-limitrange
  namespace: sample-ns
spec:
  limits:
  - default:
      cpu: 500m
      memory: 500Mi
    defaultRequest:
      cpu: 300m
      memory: 300Mi
    max:
      cpu: 1000m
      memory: 1Gi
    min:
      cpu: 100m
      memory: 100Mi
    type: Container
