apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sample-netpol
  namespace: sample-ns
spec:
  podSelector:
    matchLabels:
      run: sample-pod
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: webapp-color
    - namespaceSelector:
        matchLabels:
          name: frontend
    - namespaceSelector:
        matchLabels:
          namespace: default
      podSelector:
        matchLabels:
          app: admin
  egress:
  - to:
    - podSelector:
        matchLabels:
          name: database
    - namespaceSelector:
        matchLabels:
          name: backend
    - podSelector:
        matchExpressions:
        - key: "app"
          operator: Exists
    - podSelector:
        matchExpressions:
        - key: "tier"
          operator: In
          values:
          - backend
    ports:
    - port: 80
      protocol: TCP
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
