apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-pv
  namespace: sample-ns
  labels:
    type: sample
  annotations:
    description: "Sample pv"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: "/opt/volume/nginx"